//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PartyServer.DB
{
    public partial class APNS_PushNotifications
    {
        public int id { get; set; }
        public string DeviceToken { get; set; }
        public string AlertMessage { get; set; }
        public Nullable<int> BadgeNumber { get; set; }
        public string SoundFile { get; set; }
        public string ApplicationName { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> ProcessedOn { get; set; }
        public Nullable<System.DateTime> ViewedOnDeviceDateTime { get; set; }
    }
    
}
