//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PartyServer.DB
{
    public partial class Greeting
    {
        public Greeting()
        {
            this.Comment = new HashSet<Comment>();
            this.Like = new HashSet<Like>();
        }
    
        public int Greeting_ID { get; set; }
        public Nullable<int> Wedding_ID { get; set; }
        public string Text { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Wedding Wedding { get; set; }
        public virtual ICollection<Like> Like { get; set; }
    }
    
}
