//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PartyServer.DB
{
    public partial class Like
    {
        public int Like_ID { get; set; }
        public int Member_ID { get; set; }
        public Nullable<int> Greeting_ID { get; set; }
        public Nullable<int> Comment_ID { get; set; }
        public Nullable<int> Photo_ID { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Greeting Greeting { get; set; }
        public virtual Member Member { get; set; }
        public virtual Photo Photo { get; set; }
        public virtual Photo Photo1 { get; set; }
    }
    
}
