//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PartyServer.DB
{
    public partial class Log
    {
        public int Log_Message_ID { get; set; }
        public string Data { get; set; }
        public string Time { get; set; }
        public Nullable<int> Action { get; set; }
    }
    
}
