//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace PartyServer.DB
{
    public partial class MainDBEntities1 : DbContext
    {
        public MainDBEntities1()
            : base("name=MainDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APNS_PushNotifications> APNS_PushNotifications { get; set; }
        public DbSet<APNS_Subscriptions> APNS_Subscriptions { get; set; }
        public DbSet<Comment> Comment { get; set; }
        public DbSet<Design> Design { get; set; }
        public DbSet<Greeting> Greeting { get; set; }
        public DbSet<Invite> Invite { get; set; }
        public DbSet<Like> Like { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<Member> Member { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<Permission> Permission { get; set; }
        public DbSet<Photo> Photo { get; set; }
        public DbSet<Plan> Plan { get; set; }
        public DbSet<RehearsalDinner> RehearsalDinner { get; set; }
        public DbSet<RSVP> RSVP { get; set; }
        public DbSet<Task> Task { get; set; }
        public DbSet<TodoList> TodoList { get; set; }
        public DbSet<Wedding> Wedding { get; set; }
    }
}
