//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PartyServer.DB
{
    public partial class Permission
    {
        public Permission()
        {
            this.Member = new HashSet<Member>();
        }
    
        public int Permission_ID { get; set; }
        public int Priority { get; set; }
    
        public virtual ICollection<Member> Member { get; set; }
    }
    
}
