//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PartyServer.DB
{
    public partial class Plan
    {
        public int Plan_ID { get; set; }
        public Nullable<int> Max_Uploads { get; set; }
        public Nullable<int> SMS_Contacts_Included { get; set; }
        public Nullable<int> SMS_Wedding_Day_Included { get; set; }
        public Nullable<int> Streaming_Video { get; set; }
    }
    
}
