//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PartyServer.DB
{
    public partial class Wedding
    {
        public Wedding()
        {
            this.Greeting = new HashSet<Greeting>();
            this.Invite = new HashSet<Invite>();
            this.RehearsalDinner = new HashSet<RehearsalDinner>();
            this.TodoList = new HashSet<TodoList>();
        }
    
        public int Wedding_ID { get; set; }
        public string Date { get; set; }
        public string Place { get; set; }
        public int Groom_ID { get; set; }
        public int Bride_ID { get; set; }
        public Nullable<int> Plan_ID { get; set; }
        public Nullable<int> Image_ID { get; set; }
    
        public virtual ICollection<Greeting> Greeting { get; set; }
        public virtual ICollection<Invite> Invite { get; set; }
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual Photo Photo { get; set; }
        public virtual ICollection<RehearsalDinner> RehearsalDinner { get; set; }
        public virtual ICollection<TodoList> TodoList { get; set; }
    }
    
}
